# Generated by Django 3.1.1 on 2020-09-26 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stylometry', '0003_auto_20200927_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='pseudonym',
            field=models.CharField(default='n\x07', max_length=60, unique=True),
            preserve_default=False,
        ),
    ]
