# Generated by Django 3.1.1 on 2020-10-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stylometry', '0009_auto_20201001_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='group',
            field=models.CharField(blank=True, max_length=240, null=True, unique=True),
        ),
    ]
