# Generated by Django 3.1.1 on 2020-10-02 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stylometry', '0012_auto_20201002_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stylometry.documentgroup'),
        ),
        migrations.AlterField(
            model_name='documentgroup',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
