# Generated by Django 3.1.1 on 2020-10-02 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stylometry', '0013_auto_20201002_1225'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DocumentGroup',
            new_name='Group',
        ),
    ]
