# Generated by Django 3.1.1 on 2020-10-02 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stylometry', '0014_auto_20201002_1229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='bio',
            new_name='description',
        ),
    ]
