# Generated by Django 3.1.1 on 2021-01-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stylometry', '0023_auto_20210118_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
