# Generated by Django 3.1.1 on 2021-01-18 12:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stylometry', '0024_auto_20210118_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=240),
        ),
        migrations.AlterUniqueTogether(
            name='author',
            unique_together={('name', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('title', 'author')},
        ),
    ]
